### ISSUE TITLE
As a user, I want to be able to browse the various indoor floor maps so I can become familiar with the buildings

### ISSUE THREAD

**Issue by conso1e** [LouisBenjamin/SOEN390#13]
- [x] Place SVGs/PNG Files on the map
- [x] Research on implementing multiple floors
- [x] Implement access of multiple floors (button, slide ,etc..)

Acceptance Test 
see system test 1

Prototype Reference 
![image](https://user-images.githubusercontent.com/25642277/75122862-0a753200-5670-11ea-9f75-2ed258679ed1.png)

**Comment by LouisBenjamin** [comment]
- 40% Should be at least 2 buildings with 2 floors each
