### ISSUE TITLE
As a user I want to switch between campus maps

### ISSUE THREAD

**Issue by LouisBenjamin** [LouisBenjamin/SOEN390#26]
- [x] Add buttons that allows transition between Map
- [x] Auto-move the map to the other campus when button is clicked

Acceptance Test
![image](https://user-images.githubusercontent.com/25642277/75122723-aa31c080-566e-11ea-8cfe-f71ca02f04a5.png)

Prototype Reference 
![image](https://user-images.githubusercontent.com/25642277/75122731-bddd2700-566e-11ea-8486-4e5fbe2bef0a.png)

**Comment by conso1e** [comment]
There should be two buttons rather than a slider or single campus swap button. The reason for this is because a user should be able to pan around a campus and use the buttons to recenter themselves on the map.

**Comment by LouisBenjamin** [comment]
- 40% Done: Fix the zoom level between switches, should have default view for each where you can see the complete campus

**Comment by mosaliza** [comment]
Passed.
